### ISSUE TITLE
Duplicate CIDRs for databases delete peering connections / networking issues

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak-benchmark#571] opened 2023-10-20 16:19 UTC
When there are two databases d1 and d2 and there are two peering connections to the same cluster d1 -> c1, d2 -> c1 then removing peering connection d1 -> c1 removes also peering connection d2 -> c1

**Comment by ahus1** [comment] 2023-12-06 15:53
I suppose this can be fixed by setting `AURORA_VPC_CIDR` when setting up the database. I'll push a commit to add this to the docs. 

For a more long term solution: @ryanemerson - could we make the Aurora use instead of `192.168.0.0/16` use `192.168.x.0/24` instead, and make the "x" [globally] dynamic like we do it for the OpenShift clusters? 

This would eliminate the `AURORA_VPC_CIDR` parameter for the creation, and all follow-up command would read it from the specified cluster name. WDYT?

**Comment by ryanemerson** [comment] 2023-12-06 16:09
Yes that's the root cause as when we remove one of the peering connections we remove the `route-table` associated with `AURORA_VPC_CIDR` which will prevent traffic flowing to/from the remaining peer connection.

@ahus1 you're right that using a AURORA_VPC_CIDR unique to each DB would prevent this limitation.

**Closed** 2023-12-15 13:34 UTC
Labels: kind/bug
