### ISSUE TITLE
ROSA scheduled run has an issue with Cryostat certificates during deploy

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#894] opened 2024-07-15 12:23 UTC
[keycloak:install-keycloak] Error: UPGRADE FAILED: failed to create resource: Internal error occurred: Internal error occurred: conversion webhook for operator.cryostat.io/v1beta1, Kind=Cryostat failed: Post "[https://cryostat-operator-controller-manager-service.openshift-operators.svc:443/convert?timeout=30s](https://cryostat-operator-controller-manager-service.openshift-operators.svc/convert?timeout=30s)": tls: failed to verify certificate: x509: certificate is valid for infinispan-operator-controller-manager-service.openshift-operators, infinispan-operator-controller-manager-service.openshift-operators.svc, not cryostat-operator-controller-manager-service.openshift-operators.svc

**Comment by ahus1** [comment] 2024-07-15 12:24
@pruivo / @kami619 / @mhajas / @andyuk1986 / @mhajas - do we want to keep Cryostat? It seems we didn't use it so much recently. We might decide to remove it completely?

**Comment by kami619** [comment] 2024-07-18 02:44
I vote to deprecate it, we didn't use it for JVM analysis in the last 6 months.

**Comment by ahus1** [comment] 2024-07-18 08:09
@ryanemerson - pinging you as well. Unfortunately I forgot to mention you above. WDYT?

**Comment by ryanemerson** [comment] 2024-07-18 08:23
I think the root cause of the issue is the Cryostat 3.0.0 release. To solve the issue with this version I think we need to migrate to a new CR version.

I would propose that we just pin the Cryostat version to [v2.4.0](https://github.com/cryostatio/cryostat-operator/releases/tag/v2.4.0) our Subscription. That way we still have Cryostat if we need it at some point, but we don't have the pain of figuring out the migration. Then in the future if v2.4.0 is no longer available, we can revisit the decision to migrate/drop depending on usage.

That being said, I'm also happy to drop it as I haven't had a need for it so far.

**Comment by ahus1** [comment] 2024-07-31 06:43
Created an upstream issue, should be fixed soon: https://github.com/cryostatio/cryostat-operator/issues/924

**Comment by ebaron** [comment] 2024-08-28 14:46
Hi all, we've backported a fix for this issue to our 3.0.x branch. We'll prioritize getting a 3.0.1 release out soon for you to use.

**Comment by ebaron** [comment] 2024-09-23 20:36
> Hi all, we've backported a fix for this issue to our 3.0.x branch. We'll prioritize getting a Cryostat 3.0.1 release out soon for you to use.

Hi, just wanted to let you know that the 3.0.1 release is out now and should fix this bug you've been experiencing. Feel free to reach out if you run into any other issues.

**Closed** 2024-11-12 16:58 UTC
