### ISSUE TITLE
Running Integration tests against Keycloak on OCP with Cross DC.

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#563] opened 2023-10-04 16:04 UTC
### Description

Running Integration tests against an Keycloak on OCP with Cross DC.

We understand running all Keycloak tests with a given frequency will help us identify any unknown issues that we might introduce with the changes that are being done to Keycloak and ISPN with the Cross DC effort.

We have an option to run the [integration tests](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite) that are Arquillian based using a remote mode, this is the Epic to explore the options and run the tests as needed.

### Discussion

NA

**Comment by mhajas** [comment] 2023-10-09 18:54
Is thi a duplicate of this: https://github.com/keycloak/keycloak-benchmark/issues/483

**Closed** 2023-10-10 07:04 UTC
Labels: status/triage
